#!/bin/bash

# Demo script showing ROSA HCP CLI workflow
set +e  # Don't exit on error for demo purposes

echo "═══════════════════════════════════════════════════════════════"
echo "           ROSA HCP CLI v2.0 - Demo Workflow"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}📋 Prerequisites:${NC}"
echo "   • AWS credentials configured"
echo "   • Red Hat account with ROSA access"
echo "   • ROSA_TOKEN environment variable set"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}1. Check CLI Version${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa --version"
./bin/rosa --version
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}2. Create HCP Cluster (Interactive Mode)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa cluster create --interactive"
echo ""
echo -e "${YELLOW}[Interactive prompts would appear here]${NC}"
echo "  • Cluster Name: production-hcp"
echo "  • Region: us-west-2"
echo "  • Multi-AZ: Yes"
echo "  • Private: No"
echo "  • Compute Nodes: 3"
echo "  • Instance Type: m5.xlarge"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}3. Create HCP Cluster (Direct Command)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa cluster create \\"
echo "    --name production-hcp \\"
echo "    --region us-west-2 \\"
echo "    --version 4.14.0 \\"
echo "    --compute-nodes 3 \\"
echo "    --compute-type m5.xlarge \\"
echo "    --multi-az"
echo ""
echo -e "${CYAN}Expected output:${NC}"
echo "Creating cluster 'production-hcp'..."
echo "✓ Cluster 'production-hcp' created successfully"
echo ""
echo "Cluster Details:"
echo "  ID:          abc123xyz"
echo "  Name:        production-hcp"
echo "  State:       pending"
echo "  API URL:     https://api.production-hcp.example.com:6443"
echo "  Console URL: https://console-openshift-console.apps.production-hcp.example.com"
echo "  Region:      us-west-2"
echo "  Version:     4.14.0"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}4. List Clusters${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa cluster list"
echo ""
echo "NAME                 ID              STATE      REGION        VERSION"
echo "--------------------------------------------------------------------------------"
echo "production-hcp       abc123xyz       ready      us-west-2     4.14.0"
echo "staging-hcp         def456abc       ready      us-east-1     4.14.0"
echo "dev-hcp             ghi789def       pending    eu-west-1     4.13.18"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}5. Describe Cluster${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa cluster describe production-hcp"
echo ""
echo "Cluster Details:"
echo "  Name:        production-hcp"
echo "  ID:          abc123xyz"
echo "  State:       ready"
echo "  Region:      us-west-2"
echo "  Version:     4.14.0"
echo "  Created:     2024-01-16 10:30:00"
echo "  API URL:     https://api.production-hcp.example.com:6443"
echo "  Console URL: https://console-openshift-console.apps.production-hcp.example.com"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}6. Create NodePool (HCP-specific)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa nodepool create \\"
echo "    --cluster production-hcp \\"
echo "    --name gpu-nodes \\"
echo "    --replicas 2 \\"
echo "    --instance-type g4dn.xlarge"
echo ""
echo -e "${YELLOW}[NodePool creation would happen here]${NC}"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}7. Delete Cluster${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "$ rosa cluster delete dev-hcp"
echo ""
echo "Are you sure you want to delete cluster 'dev-hcp'? (y/N): y"
echo "Deleting cluster 'dev-hcp'..."
echo "Cluster 'dev-hcp' deletion initiated"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📌 Key Differences from v1.x:${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  ${GREEN}✓${NC} No --hosted-cp flag needed (all clusters are HCP)"
echo "  ${GREEN}✓${NC} Command structure: ${CYAN}rosa cluster create${NC} (not ${YELLOW}rosa create cluster${NC})"
echo "  ${GREEN}✓${NC} NodePools instead of MachinePools"
echo "  ${GREEN}✓${NC} Only 3 IAM roles (no Control Plane role)"
echo "  ${GREEN}✓${NC} STS-only (no mint mode)"
echo "  ${GREEN}✓${NC} Cleaner, simpler, faster!"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}                    Demo Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "To use the actual CLI:"
echo "1. Set your OCM token: export ROSA_TOKEN=<your-token>"
echo "2. Configure AWS: aws configure"
echo "3. Start creating HCP clusters!"
